apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhotelhub-app-front-deployment
spec:
  selector:
   matchLabels:
    app: webhotelhub-app-front
  replicas: 1
  template:
    metadata:
      labels:
        app: webhotelhub-app-front
    spec:
      containers:
        - name: webhotelhub-app-front
          image: renatoapaza/webhotelhub:0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: webhotelhubport