apiVersion: v1
kind: Service
metadata:
  name: webhotelhub-app-front-service
  labels:
    app: webhotelhub-app-front
spec:
  selector:
   app: webhotelhub-app-front
  type: NodePort 
  ports:
   - port: 80
     nodePort: 30300