apiVersion: v1
kind: Service
metadata:
  name: hotelhub-app-back-service
  labels:
    app: hotelhub-app-back
spec:   
  ports:
  - name: hotelhub-app-back
    port: 8080
    nodePort : 30780 
  #type: LoadBalancer
  type: NodePort
  selector:
   app: hotelhub-app-back