apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script-configmap
data:
  initdb.sh: |-
   #!/bin/bash
   set -e
   psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER reservaapp WITH PASSWORD 'qwerty';
    CREATE DATABASE hotelhub_db;
    GRANT ALL PRIVILEGES ON DATABASE hotelhub_db TO reservaapp;
   EOSQL