pipeline {
    agent any
    stages {
       /* stage("clone"){
            steps {
               // sh "git clone https://gitlab.com/uagrm1/mod5/webhotelhub.git"
               sh 'ls -ls'
            }
        }*/
        
        stage("build"){
            steps {
                dir('hotelhub'){
                    sh 'mvn clean test install'
                }
                //
            }
        }
    }

    post {
        success {
            jacoco(
                execPattern: '**/build/jacoco/*.exec',
                classPattern: '**/build/classes/java/main',
                sourcePattern: '**/src/main'
            )
        }
    }
    
}
